Feature/book browsing sorting
aaronthangnguyen/cen4010-swe1 pull request #31
Opened 2023-09-30 05:30 UTC by notrioht

### Summary

We've elevated our book management system by introducing two pivotal `GET` endpoints. The first allows users to retrieve a curated list of books based on their genre, streamlining the search process and catering to specific reading preferences. The second showcases our top 10 best-selling books, offering a quick insight into the titles that have resonated most with our audience based on copies sold. These enhancements not only optimize the browsing experience by providing tailored book recommendations but also highlight trending literature, ensuring our readers always have access to the best of our catalog.

### Changes

- Book: Add a new instance variable for rating.

- BookController: Implemented the `GET` endpoint to retrieve books by genre and top-selling books.
- BookService: Added two service methods to retrieve books by genre and top-selling books.
- BookRepository: Update the necessary query for fetching books by genre and top-selling books.
### Endpoint Details
- Purpose: Allows users or administrators to retrieve a list of books by genre and top-selling books.
- Endpoint 1: /api/books/genre/{genre}
- Endpoint 2: /api/books/top-sellers
- HTTP Method: GET
- Response 1: Returns a JSON array containing detailed information about all books by genre in the system. Each book entry includes essential details such as the book's ISBN, title, description, price, author, genre, publisher, publication year, the number of copies sold, and rating.
- Response 2: Returns a JSON array containing detailed information about the top 10 selling books in the system. Each book entry includes essential details such as the book's ISBN, title, description, price, author, genre, publisher, publication year, the number of copies sold, and rating.
    Example Response:
```json
[
 {
"id":"948e545e-b7bb-4594-8f8f-52259167e416",
  "isbn":"9780439064873",
  "name":"Harry Potter and the Chamber of Secrets",
  "description":"The second book in the Harry Potter series.",
  "price":20.99,"authorId":"c88664b2-2adb-4d1a-bc6c-0a2916be3e8c",
  "genre":"Fantasy",
  "publisher":"Scholastic",
  "yearPublished":1998,
  "copiesSold":77000000,
  "rating":0.0
 }
]
```

Test Cases
- Retrieve the list of all books by genre / by top-seller.
- Check for an empty list if there are no books in the system.
- Verify the response structure and data accuracy.

How to Test
- Pull the branch to your local setup.
- Run the application.
- Use the provided curl command or any API tool like Postman to test the endpoint.

```cmd
curl http://localhost:8080/api/books/genre/fantasy
```

2023-10-01 02:43 UTC, aaronthangnguyen commented
Approved with a few suggestions:
1. Write tests for both endpoints
2. Run `make fmt-apply` to format the project
3. Update `src/main/resources/dummy.sql`

2023-10-01 02:47 UTC, aaronthangnguyen approved these changes
@notrioht great job with this pull request!
Approved with a few suggestions:
1. Write tests for both endpoints
2. Run `make fmt-apply` to format the project
3. Update src/main/resources/dummy.sql

2023-10-01 02:47 UTC, aaronthangnguyen commented on src/main/java/com/team23/geektext/book/BookController.java
> +
Reformat with `make fmt-apply`

2023-10-05 18:36 UTC, aaronthangnguyen requested changes
![CleanShot 2023-10-05 at 14 34 13@2x](https://github.com/aaronthangnguyen/cen4010-swe1/assets/37777232/4af7e95c-689e-48dc-aeb3-dd71afbc47a3)
According to "Book Rating and Commenting" feature, rating shouldn't be Book's attribute. Rating is a class by itself. Apparently, this endpoint is dependent on @murphybrenna feature.

2023-10-12 01:14 UTC, notrioht reviewed
Reviewed

2023-10-12 01:15 UTC, notrioht reviewed
Checked

2023-10-12 02:24 UTC, notrioht reviewed
done

2023-10-12 02:24 UTC, notrioht commented on src/main/java/com/team23/geektext/book/Book.java
> +    private double rating;
done

2023-10-12 02:24 UTC, closed without merging